timezone: America/Toronto
guild_id:   1156058081759871126
channel_id: 1377855189892993197

voice_channel: gaming          # voice channel where the event will start
event_hours: 3                 # length of scheduled event

# when to post & close polls (cron-style, local TZ)
poll_post:   "Mon 09:00"       # bot will TELL users this value in its embed
poll_close:  "Wed 18:00"

time_slots:
  - Tue 21:00
  - Wed 21:00
  - Thu 21:00
  - Sat 21:00

games:
  Catan:         3
  Skribbl.io:    3
  Gartic Phone:  3
  Monopoly:      4
  Code Names:    5

# optional look-&-feel
embed_colour_time:  "#2ecc71"
embed_colour_game:  "#3498db"
